services:
  - type: pserv
    name: mysql
    env: docker
    plan: starter
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: app_db
      - key: MYSQL_USER
        value: app_user
      - key: MYSQL_PASSWORD
        sync: false
    disk:
        name: mysql
        mountPath: /var/lib/mysql
        sizeGB: 10

  - type: web
    name: GFE-web-api
    env: docker
    plan: free
    rootDir: app/backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: PORT
        value: "10000"

      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: mysql
          property: port
      - key: DB_NAME
        value: app_db
      - key: DB_USER
        value: app_user
      - key: DB_PASSWORD
        sync: false




      - key: UID
        sync: false
      - key: GID
        sync: false
      - key: USERNAME
        sync: false
      - key: REACT_APP_API_BASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: mysql2://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?encoding=utf8mb4


  # --- React（serve 版）---
  - type: web
    name: GFE-web
    env: docker
    plan: free
    rootDir: app/frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: RAILS_API_URL
        sync: false
