services:
  - type: pserv
    name: mysql
    plan: standard
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: mysql
      - key: MYSQL_USER
        value: mysql
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    

  - type: web
    name: GFE-web-api
    env: docker
    plan: free
    rootDir: app/backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: UID
        sync: false
      - key: GID
        sync: false
      - key: USERNAME
        sync: false
      - key: REACT_APP_API_BASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          type: pserv
          name: mysql
          property: connectionString

  # --- React（serve 版）---
  - type: web
    name: GFE-web
    env: docker
    plan: free
    rootDir: app/frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: RAILS_API_URL
        sync: false
